[package]
org = "sanjiva"
name = "datamodel"
version = "0.1.0"

[build-options]
observabilityIncluded = true

[persist]
datastore = "inmemory"
module = "datamodel"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.inmemory-native"
version = "1.2.0"

